repos:
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.3
    hooks:
    - id: nbqa-black
    - id: nbqa-isort 
    - id: nbqa-flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
